Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2022-11, with the labels that each got.

#2399 SPCTR-2010 Fix: Added missing upload in include and removed localized blocks from src/blocks.
  classes/class-uagb-init-blocks.php
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/forms-upload/block.php
  src/blocks/cf7-designer/block.js
  src/blocks/columns/edit.js
  src/blocks/forms/child-blocks/upload/block.js
  src/blocks/forms/edit.js
  src/blocks/gf-designer/block.js
  src/blocks/how-to/child-blocks/step/block.js
  src/blocks/post/post-carousel/edit.js
  src/blocks/post/post-grid/edit.js
  src/blocks/post/post-masonry/edit.js
  src/blocks/timeline/post-timeline/render.js
Labels: create zip

#2430 SPCTR-1933 - Improvement: Automatic Block Prioritization
  README.md
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  classes/class-spectra-block-prioritization.php
  classes/class-uagb-loader.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/advanced-heading/block.php
  includes/blocks/blockquote/block.php
  includes/blocks/buttons/block.php
  includes/blocks/call-to-action/block.php
  includes/blocks/cf7-styler/block.php
  includes/blocks/columns/block.php
  includes/blocks/container/block.php
  includes/blocks/content-timeline/block.php
  includes/blocks/faq/block.php
  includes/blocks/forms/block.php
  includes/blocks/gf-styler/block.php
  includes/blocks/google-map/block.php
  includes/blocks/how-to/block.php
  includes/blocks/icon-list/block.php
  includes/blocks/image/block.php
  includes/blocks/info-box/block.php
  includes/blocks/inline-notice/block.php
  includes/blocks/lottie/block.php
  includes/blocks/marketing-button/block.php
  includes/blocks/post-carousel/block.php
  includes/blocks/post-grid/block.php
  includes/blocks/post-masonry/block.php
  includes/blocks/post-timeline/block.php
  includes/blocks/restaurant-menu/block.php
  includes/blocks/review/block.php
  includes/blocks/section/block.php
  includes/blocks/social-share/block.php
  includes/blocks/star-rating/block.php
  includes/blocks/table-of-contents/block.php
  includes/blocks/tabs/block.php
  includes/blocks/taxonomy-list/block.php
  includes/blocks/team/block.php
  includes/blocks/testimonial/block.php
  includes/blocks/wp-search/block.php
  readme.txt
  src/blocks.js
Labels: php, javascript, admin, editor

#2414 SPCTR-1937 UAG Number Control Redesign
  dist/blocks.asset.php
  dist/blocks.js
  src/components/number-control/editor.lazy.scss
  src/components/number-control/index.js
Labels: enhancement

#2401 SPCTR-1970 Slider block basic
  assets/css/blocks/slider-child.css
  assets/css/blocks/slider.css
  assets/css/swiper-bundle.min.css
  assets/js/swiper-bundle.min.js
  classes/class-uagb-block-module.php
  classes/class-uagb-config.php
  dist/blocks-placeholder.js
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/slider/attributes.php
  includes/blocks/slider/block.php
  includes/blocks/slider/frontend.js.php
  package-lock.json
  package.json
  src/blocks.js
  src/blocks/slider-child/attributes.js
  src/blocks/slider-child/block.js
  src/blocks/slider-child/edit.js
  src/blocks/slider-child/render.js
  src/blocks/slider-child/save.js
  src/blocks/slider-child/settings.js
  src/blocks/slider-child/styling.js
  src/blocks/slider/attributes.js
  src/blocks/slider/block.js
  src/blocks/slider/edit.js
  src/blocks/slider/editor.lazy.scss
  src/blocks/slider/presets.js
  src/blocks/slider/render.js
  src/blocks/slider/save.js
  src/blocks/slider/settings.js
  src/blocks/slider/style.scss
  src/blocks/slider/styling.js
  src/blocks/timeline/content-timeline/render.js
Labels: enhancement

#2293 SPCTR-602 - New: Image Gallery
  README.md
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/common/block-icons.js
  admin-core/package-lock.json
  assets/css/blocks/image-gallery.css
  assets/js/image-gallery.js
  assets/js/image-gallery.min.js
  blocks-config/blocks-attributes/getBlocksDefaultAttributes.js
  blocks-config/blocks-config.php
  blocks-config/image-gallery/class-spectra-image-gallery.php
  blocks-config/uagb-controls/block-icons.js
  blocks-config/uagb-controls/generateBorderRadius.js
  blocks-config/uagb-controls/generateSpacing.js
  blocks-config/uagb-controls/getMatrixAlignment.js
  blocks-config/uagb-controls/getPrecisePercentage.js
  classes/class-spectra-block-prioritization.php
  classes/class-uagb-block-helper.php
  classes/class-uagb-block-js.php
  classes/class-uagb-block-module.php
  classes/class-uagb-config.php
  classes/class-uagb-helper.php
  classes/class-uagb-loader.php
  classes/class-uagb-post-assets.php
  classes/class-uagb-scripts-utils.php
  dist/blocks-placeholder.js
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/image-gallery/attributes.php
  includes/blocks/image-gallery/block.php
  includes/blocks/image-gallery/frontend.css.php
  includes/blocks/image-gallery/frontend.js.php
  readme.txt
  src/blocks.js
  src/blocks/image-gallery/attributes.js
  src/blocks/image-gallery/block.js
  src/blocks/image-gallery/components/ImageGallery.js
  src/blocks/image-gallery/components/InitialSelector.js
  src/blocks/image-gallery/edit.js
  src/blocks/image-gallery/editor.lazy.scss
  src/blocks/image-gallery/presets.js
  src/blocks/image-gallery/render.js
  src/blocks/image-gallery/settings.js
  src/blocks/image-gallery/style.scss
  src/blocks/image-gallery/styling.js
  src/components/multimedia-select/index.js
  wpml-config.xml
Labels: enhancement, php, javascript, css

#2422 SPCTR-1916 - New: Instagram Admin Dashboard UI.
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/common/block-icons.js
  admin-core/assets/src/common/common.scss
  admin-core/assets/src/dashboard-app/pages/settings/BlockSettings.js
  admin-core/assets/src/dashboard-app/pages/settings/RollBackConfirmPopup.js
  admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
  admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUsers.js
  admin-core/package-lock.json
  blocks-config/uagb-controls/block-icons.js
  dist/blocks.asset.php
  dist/blocks.js
Labels: javascript, admin

#2433 SPCTR 2002 - Created Spectra Text Control/Component and replaced old Gutenberg TextControls and TextareaControls
  README.md
  blocks-config/blocks-attributes/getBlocksDefaultAttributes.js
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  readme.txt
  src/blocks/blockquote/settings.js
  src/blocks/buttons-child/settings.js
  src/blocks/call-to-action/settings.js
  src/blocks/forms/child-blocks/accept/settings.js
  src/blocks/forms/child-blocks/email/settings.js
  src/blocks/forms/child-blocks/hidden/settings.js
  src/blocks/forms/child-blocks/name/settings.js
  src/blocks/forms/child-blocks/textarea/settings.js
  src/blocks/forms/child-blocks/toggle/settings.js
  src/blocks/forms/child-blocks/url/settings.js
  src/blocks/forms/settings.js
  src/blocks/google-map/settings.js
  src/blocks/how-to/child-blocks/step/settings.js
  src/blocks/icon-list-child/settings.js
  src/blocks/image/settings.js
  src/blocks/info-box/settings.js
  src/blocks/lottie/settings.js
  src/blocks/marketing-button/settings.js
  src/blocks/post/post-carousel/edit.js
  src/blocks/post/post-grid/attributes.js
  src/blocks/post/post-grid/settings.js
  src/blocks/post/post-masonry/edit.js
  src/blocks/review/settings.js
  src/blocks/taxonomy-list/settings.js
  src/blocks/team/settings.js
  src/blocks/timeline/content-timeline-child/settings.js
  src/blocks/timeline/post-timeline/settings.js
  src/blocks/wp-search/settings.js
  src/components/text-control/editor.lazy.scss
  src/components/text-control/index.js
Labels: enhancement

#2442 SPCTR-1833 - New: Matrix Alignment Control
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/image-gallery/settings.js
  src/blocks/image/settings.js
  src/components/matrix-alignment-control/editor.lazy.scss
  src/components/matrix-alignment-control/index.js
Labels: javascript, editor

#1365 SPCTR-548 - New: Counter Block
  README.md
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/common/block-icons.js
  assets/css/blocks/counter.css
  assets/js/countUp.min.js
  assets/js/uagb-counter.js
  assets/js/uagb-counter.min.js
  blocks-config/blocks-attributes/getBlocksDefaultAttributes.js
  blocks-config/uagb-controls/block-icons.js
  classes/class-spectra-block-prioritization.php
  classes/class-uagb-block-module.php
  classes/class-uagb-config.php
  dist/blocks-placeholder.js
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/counter/attributes.php
  includes/blocks/counter/block.php
  includes/blocks/counter/frontend.css.php
  includes/blocks/counter/frontend.js.php
  readme.txt
  src/blocks.js
  src/blocks/counter/attributes.js
  src/blocks/counter/block.js
  src/blocks/counter/component/CounterIcon.js
  src/blocks/counter/edit.js
  src/blocks/counter/presets.js
  src/blocks/counter/render.js
  src/blocks/counter/save.js
  src/blocks/counter/settings.js
  src/blocks/counter/style.scss
  src/blocks/counter/styling.js
  src/components/number-control/index.js
  wpml-config.xml
Labels: enhancement

#2438 SPCTR-1905 Slider block
  assets/css/blocks/slider.css
  blocks-config/uagb-controls/addBlockEditorDynamicStyles.js
  classes/class-uagb-block-module.php
  classes/class-uagb-config.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/common-editor.css
  dist/style-blocks.css
  includes/blocks/slider-child/attributes.php
  includes/blocks/slider-child/frontend.css.php
  includes/blocks/slider/attributes.php
  includes/blocks/slider/block.php
  includes/blocks/slider/frontend.css.php
  includes/blocks/slider/frontend.js.php
  package-lock.json
  package.json
  src/blocks/extensions/advanced-settings/index.js
  src/blocks/slider-child/attributes.js
  src/blocks/slider-child/edit.js
  src/blocks/slider-child/render.js
  src/blocks/slider-child/save.js
  src/blocks/slider-child/settings.js
  src/blocks/slider-child/styling.js
  src/blocks/slider/attributes.js
  src/blocks/slider/edit.js
  src/blocks/slider/editor.lazy.scss
  src/blocks/slider/render.js
  src/blocks/slider/save.js
  src/blocks/slider/settings.js
  src/blocks/slider/style.scss
  src/blocks/slider/styling.js
  src/common-editor.scss
Labels: enhancement

#2099 SPCTR-1489 - Login block admin settings Page
  admin-core/ajax/common-settings.php
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/common/block-icons.js
  admin-core/assets/src/common/common.scss
  admin-core/assets/src/dashboard-app/pages/settings/BlockSettings.js
  admin-core/assets/src/dashboard-app/pages/settings/Settings.js
  admin-core/assets/src/dashboard-app/pages/settings/block-settings/Login.js
  admin-core/assets/src/store/globalDataReducer.js
  admin-core/assets/src/store/globalDataStore.js
  admin-core/assets/src/utils/setInitialState.js
  admin-core/inc/admin-helper.php
  admin-core/inc/admin-menu.php
  admin-core/package-lock.json
  blocks-config/uagb-controls/block-icons.js
  classes/class-uagb-init-blocks.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/common-editor.css
  src/blocks/extensions/copy-paste-styles/index.js
  src/common-editor.scss
  src/components/multi-buttons-control/index.js
  src/components/multi-select-control/index.js
  src/components/reset/index.js
  src/components/responsive-border/index.js
  src/components/separator/editor.lazy.scss
  src/components/separator/index.js
  src/styles/gutenberg-override.scss
Labels: enhancement

#2448 Improvement: Updated Changelogs
  README.md
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  dist/blocks-placeholder.js
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/how-to/block.php
  includes/blocks/table-of-contents/block.php
  readme.txt
  src/blocks/how-to/block.js
  src/blocks/table-of-contents/block.js
Labels: php, javascript, admin, editor

#2450 SPCTR-2052 Package Testing - Presets - 'Show icon' and some button border features not working for some presets
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/call-to-action/presets.js
  src/blocks/info-box/presets.js
  src/blocks/post/post-carousel/presets.js
  src/blocks/post/post-grid/presets.js
  src/blocks/post/post-masonry/presets.js
Labels: bug

#2459 SPCTR-2055 Slider Arrow Padding Option
  assets/css/blocks/slider.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/slider/attributes.php
  includes/blocks/slider/frontend.css.php
  src/blocks/slider/attributes.js
  src/blocks/slider/editor.lazy.scss
  src/blocks/slider/render.js
  src/blocks/slider/save.js
  src/blocks/slider/settings.js
  src/blocks/slider/style.scss
  src/blocks/slider/styling.js
Labels: enhancement

#2467 SPCTR-2054 Slider arrows toggle option
  assets/css/blocks/slider.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/slider/attributes.php
  includes/blocks/slider/frontend.js.php
  src/blocks/slider/attributes.js
  src/blocks/slider/editor.lazy.scss
  src/blocks/slider/render.js
  src/blocks/slider/save.js
  src/blocks/slider/settings.js
  src/blocks/slider/style.scss
Labels: enhancement

#2460 SPCTR-1957 Counter CLS: Added CLS support
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/counter/attributes.js
  src/blocks/counter/component/CounterIcon.js
  src/blocks/counter/render.js
Labels: enhancement

#2458 SPCTR-2023 Counter - Added support for UAGCopyPaste feature
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/counter/attributes.js
Labels: bug

#2471 SPCTR-2075 Counter: Fixed erroneous display conditions for Icon/Image component (Also, image not visible when an icon is removed)
  assets/css/blocks/countdown.css
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/counter/render.js
  src/blocks/counter/save.js
Labels: bug

#2482 Improvement: Updated Changelog for 2.0.16
  README.md
  readme.txt
Labels: ready-to-merge

#2484 New: SPCTR-2050 - Added Version Numbers and License Status
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/common/colors-config.scss
  admin-core/assets/src/common/common.scss
  admin-core/assets/src/dashboard-app/MainNav.js
  admin-core/assets/src/dashboard-app/PluginStats.js
  admin-core/assets/src/dashboard-app/pages/blocks/FilterTabs.js
  admin-core/assets/src/dashboard-app/pages/settings/MyAccount.js
  admin-core/assets/src/dashboard-app/pages/settings/Settings.js
  admin-core/assets/src/dashboard-app/pages/settings/SettingsIcons.js
  admin-core/inc/admin-menu.php
Labels: enhancement, admin

#2486 New: SPCTR-2050 - Pro Block Cards and Badges
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/pages/blocks/BlockCard.js
  admin-core/assets/src/dashboard-app/pages/blocks/BlockCardsGroup.js
  admin-core/assets/src/dashboard-app/pages/blocks/DisplayConditionsExtension.js
  admin-core/assets/src/dashboard-app/pages/blocks/DynamicContentExtension.js
  admin-core/assets/src/dashboard-app/pages/blocks/Extensions.js
  admin-core/assets/src/dashboard-app/pages/blocks/FilterTabs.js
  admin-core/assets/src/dashboard-app/pages/blocks/MasonryGalleryExtension.js
  admin-core/assets/src/dashboard-app/pages/blocks/ResponsiveConditionsExtention.js
  classes/class-spectra-block-prioritization.php
  classes/class-uagb-init-blocks.php
  classes/class-uagb-loader.php
  includes/blocks/advanced-heading/block.php
  includes/blocks/blockquote/block.php
  includes/blocks/buttons/block.php
  includes/blocks/call-to-action/block.php
  includes/blocks/cf7-styler/block.php
  includes/blocks/columns/block.php
  includes/blocks/container/block.php
  includes/blocks/content-timeline/block.php
  includes/blocks/faq/block.php
  includes/blocks/forms/block.php
  includes/blocks/gf-styler/block.php
  includes/blocks/google-map/block.php
  includes/blocks/how-to/block.php
  includes/blocks/icon-list/block.php
  includes/blocks/image/block.php
  includes/blocks/info-box/block.php
  includes/blocks/inline-notice/block.php
  includes/blocks/login/block.php
  includes/blocks/lottie/block.php
  includes/blocks/marketing-button/block.php
  includes/blocks/post-carousel/block.php
  includes/blocks/post-grid/block.php
  includes/blocks/post-masonry/block.php
  includes/blocks/post-timeline/block.php
  includes/blocks/register/block.php
  includes/blocks/restaurant-menu/block.php
  includes/blocks/review/block.php
  includes/blocks/section/block.php
  includes/blocks/social-share/block.php
  includes/blocks/star-rating/block.php
  includes/blocks/table-of-contents/block.php
  includes/blocks/tabs/block.php
  includes/blocks/taxonomy-list/block.php
  includes/blocks/team/block.php
  includes/blocks/testimonial/block.php
  includes/blocks/wp-search/block.php
Labels: enhancement, admin

#2494 SPCTR-2088 - Pro Base Package Fixes
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/PluginStats.js
  admin-core/assets/src/dashboard-app/pages/settings/MyAccount.js
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/buttons-child/settings.js
  src/blocks/container/settings.js
Labels: php, javascript, admin, editor
