Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2022-07, with the labels that each got.

#1803 SPCTR-1142 Social Share- Upgrade to responsive alignment
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/social-share/settings.js
  includes/blocks/social-share/attributes.php
  includes/blocks/social-share/frontend.css.php
  src/blocks/social-share/attributes.js
  src/blocks/social-share/settings.js
  src/blocks/social-share/styling.js
Labels: enhancement, javascript, needs review

#1816 SPCTR-1189 - Google Maps - Added styling.js, frontend.css.php and Responsive Height Functionality
  classes/class-uagb-block-module.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/google-map/render.js
  dist/chunks/google-map/settings.js
  includes/blocks/google-map/attributes.php
  includes/blocks/google-map/frontend.css.php
  src/blocks/google-map/attributes.js
  src/blocks/google-map/edit.js
  src/blocks/google-map/render.js
  src/blocks/google-map/save.js
  src/blocks/google-map/settings.js
  src/blocks/google-map/styling.js
Labels: enhancement, php, javascript, needs review

#1794 SPCTR-1026 Fix: block icon alignment issue in the editor
  blocks-config/uagb-controls/block-icons.js
  dist/blocks.asset.php
  dist/blocks.js
Labels: bug

#1789 SPCTR-1199 - Fixed lottie frontend alignment
  includes/blocks/lottie/frontend.css.php
Labels: bug, php, needs review

#1799 SPCTR-1135 - Fix: Container block frontend alignment issue
  includes/blocks/container/frontend.css.php
Labels: bug

#1813 SPCTR-1220 - Fix: Renamed Image Size Dropdown
  dist/chunks/post-timeline/settings.js
  src/blocks/timeline/post-timeline/settings.js
Labels: javascript

#1796 SPCTR-1164 - Fix: Deformed Form Toggle
  assets/css/blocks/forms.css
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/form/radio-render.js
  dist/chunks/form/radio-settings.js
  dist/chunks/form/textarea-render.js
  dist/chunks/google-map/render.js
  dist/chunks/how-to/render.js
  dist/chunks/how-to/settings.js
  dist/chunks/lottie/render.js
  dist/chunks/post-carousel/render.js
  dist/chunks/post-grid/blog.js
  dist/chunks/post-masonry/react-masonry-component.js
  dist/chunks/post-timeline/render.js
  dist/chunks/table-of-contents/render.js
  dist/chunks/testimonial/render.js
  dist/chunks/testimonial/settings.js
  dist/style-blocks.css
  includes/blocks/forms/frontend.css.php
  src/blocks/forms/child-blocks/radio/attributes.js
  src/blocks/forms/child-blocks/radio/render.js
  src/blocks/forms/child-blocks/radio/save.js
  src/blocks/forms/child-blocks/radio/settings.js
  src/blocks/forms/style.scss
  src/blocks/forms/styling.js
Labels: php, javascript

#1792 SPCTR-1167 - Fix: button block typography attribute value save not working
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/buttons-child/settings.js
  includes/blocks/buttons-child/attributes.php
  includes/blocks/buttons/frontend.css.php
  src/blocks/buttons-child/attributes.js
  src/blocks/buttons-child/settings.js
  src/blocks/buttons-child/styling.js
  src/blocks/buttons/attributes.js
Labels: bug

#1823 SPCTR-1245 - Icon list: Border width and radius is not working for mobile mode on frontend
  includes/blocks/icon-list/frontend.css.php
Labels: bug, php, needs review

#1807 SPCTR-1208 - Tabs: Horizontal Style 4 not looking as expected in editor
  dist/chunks/tabs/render.js
  src/blocks/tabs/editor.lazy.scss
Labels: bug, needs review, css

#1775 SPCTR-1180 - Fix: Container box shadow transition issue
  assets/css/blocks/container.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/container/style.scss
Labels: bug

#1826 SPCTR-1236 Forms - Removed debugging line for button padding-top (tablet)
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/form/settings.js
  src/blocks/forms/settings.js
  src/blocks/forms/styling.js
Labels: bug, javascript, needs review

#1841 SPCTR-1103 Info Box - Responsive Alignment
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/info-box/settings.js
  includes/blocks/info-box/attributes.php
  includes/blocks/info-box/frontend.css.php
  src/blocks/info-box/attributes.js
  src/blocks/info-box/settings.js
  src/blocks/info-box/styling.js
Labels: enhancement, php, javascript, needs review

#1829 SPCTR-1253 Post Blocks - Removed '(Untitled)' label for untitled posts in the editor
  blocks-config/post-timeline/class-uagb-post-timeline.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/post-timeline/render.js
  src/blocks/post/post-title/edit.js
  src/blocks/timeline/post-timeline/components/Title.js
Labels: bug, javascript

#1834 SPCTR-1237 Form Submit Button - Remove border width in editor added by browser's user agent
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/form/render.js
  src/blocks/forms/editor.lazy.scss
  src/blocks/forms/styling.js
Labels: bug, javascript, needs review

#1759 SPCTR-958 Add object fit option for image block
  composer.json
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/buttons/settings.js
  dist/chunks/column/settings.js
  dist/chunks/columns/settings.js
  dist/chunks/container/settings.js
  dist/chunks/image/settings.js
  dist/chunks/section/settings.js
  dist/chunks/tabs/settings.js
  dist/chunks/testimonial/settings.js
  includes/blocks/container/attributes.php
  includes/blocks/faq/frontend.css.php
  includes/blocks/icon-list/frontend.css.php
  includes/blocks/image/attributes.php
  includes/blocks/image/frontend.css.php
  includes/blocks/lottie/frontend.css.php
  includes/blocks/social-share/frontend.css.php
  src/blocks/image/attributes.js
  src/blocks/image/settings.js
  src/blocks/image/styling.js
Labels: enhancement

#1838 SPCTR-1246 - Fix: Icon List Block Stack Issue
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/icon-list/settings.js
  includes/blocks/icon-list/attributes.php
  includes/blocks/icon-list/frontend.css.php
  src/blocks/icon-list/attributes.js
  src/blocks/icon-list/settings.js
  src/blocks/icon-list/styling.js
Labels: bug

#1862 button block - Fix Global Typography not working issue
  includes/blocks/buttons/frontend.css.php
Labels: bug

#1853 SPCTR-1277 Icon List - 2 settings sections open under General tab
  dist/chunks/container/settings.js
  dist/chunks/icon-list/settings.js
  src/blocks/container/settings.js
  src/blocks/icon-list/settings.js
Labels: bug, javascript

#1851 SPCTR-1205 - Fix: Admin Tab Colors
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/common/colors-config.scss
  admin-core/assets/src/common/common.scss
  admin-core/assets/src/dashboard-app/MainNav.js
  admin-core/assets/src/dashboard-app/pages/blocks/BlockCard.js
  admin-core/assets/src/dashboard-app/pages/blocks/DisplayConditionsExtension.js
  admin-core/assets/src/dashboard-app/pages/blocks/FilterTabs.js
  admin-core/assets/src/dashboard-app/pages/blocks/MasonryGalleryExtension.js
  admin-core/assets/src/dashboard-app/pages/blocks/ResponsiveConditionsExtention.js
  admin-core/assets/src/dashboard-app/pages/settings/AssetsGeneration.js
  admin-core/assets/src/dashboard-app/pages/settings/BlockSettings.js
  admin-core/assets/src/dashboard-app/pages/settings/BlocksEditorSpacing.js
  admin-core/assets/src/dashboard-app/pages/settings/ContentWidth.js
  admin-core/assets/src/dashboard-app/pages/settings/RegenerateAssets.js
  admin-core/assets/src/dashboard-app/pages/settings/RollBack.js
  admin-core/assets/src/dashboard-app/pages/settings/RollBackConfirmPopup.js
  admin-core/assets/src/dashboard-app/pages/settings/Settings.js
  admin-core/assets/src/dashboard-app/pages/welcome/Welcome.js
  admin-core/inc/admin-menu.php
Labels: javascript, css

#1836 SPCTR-1208 - Fix: Tabs block layout improvement
  blocks-config/uagb-controls/addBlockEditorDynamicStyles.js
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/tabs/render.js
  src/blocks/tabs/editor.lazy.scss
Labels: bug, enhancement

#1825 SPCTR-1038 - Fix: Typography Components collapse panels not working if disable Collapse Panels
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/advanced-heading/settings.js
  dist/chunks/buttons-child/settings.js
  dist/chunks/columns/settings.js
  dist/chunks/container/settings.js
  dist/chunks/image/settings.js
  dist/chunks/section/settings.js
  dist/chunks/taxonomy-list/settings.js
  dist/chunks/wp-search/settings.js
  src/blocks/advanced-heading/settings.js
  src/blocks/buttons-child/settings.js
  src/blocks/columns/settings.js
  src/blocks/container/settings.js
  src/blocks/image/settings.js
  src/blocks/section/settings.js
  src/blocks/taxonomy-list/settings.js
  src/blocks/wp-search/settings.js
  src/components/box-shadow/index.js
  src/components/text-shadow/index.js
  src/components/typography/index.js
Labels: bug

#1849 SPCTR-1266 SPCTR-1293 Content Timeline - 'Invalid Date' shown on frontend for dd.mm.yyyy format
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/advanced-heading/settings.js
  dist/chunks/blockquote/settings.js
  dist/chunks/buttons-child/settings.js
  dist/chunks/call-to-action/settings.js
  dist/chunks/cf7-styler/settings.js
  dist/chunks/columns/settings.js
  dist/chunks/container/settings.js
  dist/chunks/content-timeline-child/render.js
  dist/chunks/content-timeline/settings.js
  dist/chunks/faq/settings.js
  dist/chunks/form/date-settings.js
  dist/chunks/form/email-settings.js
  dist/chunks/form/name-settings.js
  dist/chunks/form/phone-settings.js
  dist/chunks/form/settings.js
  dist/chunks/form/textarea-settings.js
  dist/chunks/form/url-settings.js
  dist/chunks/gf-styler/settings.js
  dist/chunks/google-map/settings.js
  dist/chunks/how-to/settings.js
  dist/chunks/how-to/step-settings.js
  dist/chunks/icon-list/settings.js
  dist/chunks/image/settings.js
  dist/chunks/info-box/settings.js
  dist/chunks/marketing-button/settings.js
  dist/chunks/post-grid/settings.js
  dist/chunks/post-timeline/render.js
  dist/chunks/post-timeline/settings.js
  dist/chunks/price-list/settings.js
  dist/chunks/review/settings.js
  dist/chunks/section/settings.js
  dist/chunks/social-share-child/settings.js
  dist/chunks/social-share/settings.js
  dist/chunks/tabs/settings.js
  dist/chunks/taxonomy-list/settings.js
  dist/chunks/team/settings.js
  dist/chunks/testimonial/settings.js
  dist/chunks/wp-search/settings.js
  src/blocks/timeline/content-timeline-child/render.js
  src/blocks/timeline/content-timeline-child/save.js
Labels: bug, javascript, needs review

#1865 SPCTR-1286 Buttons Child Block - Text hover color not working for icon in editor
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/buttons-child/styling.js
Labels: bug, javascript

#1890 SPCTR-1302 Lottie Block - Added note for Speed control
  dist/chunks/lottie/settings.js
  src/blocks/lottie/settings.js
Labels: bug, javascript

#1875 SPCTR-1294 Table of Contents/TOC - Columns settings control not working
  assets/css/blocks/table-of-contents.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/table-of-contents/render.js
  dist/style-blocks.css
  includes/blocks/table-of-contents/frontend.css.php
  src/blocks/table-of-contents/editor.lazy.scss
  src/blocks/table-of-contents/style.scss
  src/blocks/table-of-contents/styling.js
Labels: bug, php, javascript, css

#1904 SPCTR-1329 FAQ - Border radius not working properly for questions div
  assets/css/blocks/faq.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/faq/style.scss
Labels: bug, php, javascript, css

#1909 SPCTR-1342 FAQ Line height fix for Astra theme
  assets/css/blocks/faq.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/faq/style.scss
Labels: bug, css

#1910 SPCTR-630 Global Settings: Renamed 'Advanced' tab to 'Other'
  dist/blocks.asset.php
  dist/blocks.js
  src/components/inspector-tabs/InspectorTabs.js
Labels: bug, javascript

#1926 SPCTR-1361 Price List - Incorrect default attribute fix
  includes/blocks/restaurant-menu/attributes.php
Labels: bug, php

#1927 SPCTR-1366 Advanced Column - Gradient type background not displayed on frontend
  includes/blocks/columns/attributes.php
Labels: bug, php

#1929 SPCTR-1111 Icon List - Added New Spacing Options
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/icon-list-child/render.js
  dist/chunks/icon-list-child/settings.js
  dist/chunks/icon-list/settings.js
  includes/blocks/icon-list-child/attributes.php
  includes/blocks/icon-list-child/frontend.css.php
  includes/blocks/icon-list/attributes.php
  includes/blocks/icon-list/frontend.css.php
  src/blocks/icon-list-child/attributes.js
  src/blocks/icon-list-child/render.js
  src/blocks/icon-list-child/settings.js
  src/blocks/icon-list-child/styling.js
  src/blocks/icon-list/attributes.js
  src/blocks/icon-list/settings.js
  src/blocks/icon-list/styling.js
Labels: enhancement, php, javascript

#1957 SPCTR-1212 - Fix: Masonry Height Removal
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/post/styling.js
Labels: javascript

#1949 SPCTR-910 Table of Content - Separator Feature
  blocks-config/table-of-content/class-uagb-table-of-content.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/table-of-contents/render.js
  dist/chunks/table-of-contents/settings.js
  includes/blocks/table-of-contents/attributes.php
  includes/blocks/table-of-contents/frontend.css.php
  src/blocks/table-of-contents/attributes.js
  src/blocks/table-of-contents/render.js
  src/blocks/table-of-contents/settings.js
  src/blocks/table-of-contents/styling.js
Labels: enhancement, php, javascript

#1956 SPCTR-1039 All Blocks - Shifted all alignment controls to General Tab
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/blockquote/settings.js
  dist/chunks/form/settings.js
  dist/chunks/gf-styler/settings.js
  dist/chunks/image/settings.js
  dist/chunks/post-grid/settings.js
  dist/chunks/testimonial/settings.js
  src/blocks/blockquote/settings.js
  src/blocks/forms/settings.js
  src/blocks/gf-designer/settings.js
  src/blocks/image/settings.js
  src/blocks/post/post-grid/settings.js
  src/blocks/post/post-masonry/edit.js
  src/blocks/testimonial/settings.js
Labels: javascript

#1964 SPCTR-646 Admin page video custom screen at end spctr 646
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/pages/welcome/Welcome.js
Labels: enhancement, javascript

#1974 SPCTR-963 - Fix: Updated Keywords and Block Title for Google Maps
  dist/blocks-placeholder.js
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/google-map/block.php
  src/blocks/google-map/block.js
Labels: php, javascript

#1975 SPCTR-1033 - Fix: Updated Hint Text for All Flex Properties
  dist/chunks/container/settings.js
  src/blocks/container/settings.js
Labels: javascript

#1976 SPCTR-1438 Responsive Slider - Unable to set 0 value
  dist/blocks.asset.php
  dist/blocks.js
  src/components/responsive-slider/index.js
Labels: bug, javascript
