Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2022-05, with the labels that each got.

#1498 Improvement - Testimonial Block acceptance
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/testimonial/render.js
  includes/blocks/testimonial/attributes.php
  package-lock.json
  src/blocks/testimonial/attributes.js
  src/blocks/testimonial/editor.lazy.scss
Labels: enhancement

#1497 Update - Toggle Component
  dist/common-editor.css
  src/common-editor.scss
Labels: enhancement

#1533 SPCTR-744 - Container Color Settings
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/container/settings.js
  includes/blocks/container/attributes.php
  includes/blocks/container/frontend.css.php
  src/blocks/container/attributes.js
  src/blocks/container/render.js
  src/blocks/container/save.js
  src/blocks/container/settings.js
  src/blocks/container/styling.js
Labels: enhancement, php, javascript

#1519 SPCTR-605 - Improvement: Gravity form acceptance improvement
  assets/css/blocks/gf-styler.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/gf-styler/settings.js
  dist/style-blocks.css
  includes/blocks/social-share/frontend.css.php
  src/blocks/gf-designer/settings.js
  src/blocks/gf-designer/style.scss
  src/blocks/gf-designer/styling.js
Labels: enhancement

#1573 SPCTR-820 Fix: Info box icon fix gets changed while switching Presets
  dist/chunks/info-box/settings.js
  src/blocks/info-box/presets.js
Labels: bug

#1572 SPCTR-815 Fix: Search bar goes outside the container
  assets/css/blocks/wp-search.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/wp-search/render.js
  dist/style-blocks.css
  src/blocks/wp-search/editor.lazy.scss
  src/blocks/wp-search/style.scss
  src/blocks/wp-search/styling.js
Labels: bug

#1566 SPCTR-812 Fix: Title Margin not getting applied for vertical style presets
  assets/css/blocks/tabs.css
  dist/blocks.style.css
  dist/chunks/tabs/render.js
  dist/style-blocks.css
  src/blocks/tabs/editor.lazy.scss
  src/blocks/tabs/style.scss
Labels: bug

#1553 SPCTR-784 : Blockquote Fixes (R3)
  assets/css/blocks/blockquote.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/blockquote/settings.js
  dist/style-blocks.css
  includes/blocks/blockquote/attributes.php
  includes/blocks/blockquote/frontend.css.php
  src/blocks/blockquote/attributes.js
  src/blocks/blockquote/settings.js
  src/blocks/blockquote/style.scss
  src/blocks/blockquote/styling.js
Labels: bug, enhancement, needs review

#1571 SPCTR-710 - Fix: CTA Alignment issue
  includes/blocks/call-to-action/frontend.css.php
Labels: bug, php

#1575 SPCTR-826 : Buttons Block R3 Gradient Control Alignment Fix
  assets/css/blocks/buttons-child.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/buttons-child/style.scss
Labels: needs review, css

#1569 SPCTR-804 : Added Responsive Stacking, Bug fixes
  assets/css/blocks/star-rating.css
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/star-rating/settings.js
  dist/style-blocks.css
  includes/blocks/star-rating/attributes.php
  includes/blocks/star-rating/frontend.css.php
  src/blocks/star-rating/attributes.js
  src/blocks/star-rating/settings.js
  src/blocks/star-rating/style.scss
  src/blocks/star-rating/styling.js
Labels: bug, enhancement, php, javascript

#1586 SPCTR-841 : R2 Tab Block - Tab Icon Not Vertically Centred
  assets/css/blocks/tabs.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/tabs/style.scss
Labels: bug, needs review, css

#1591 SPCTR-848 Post Grid Block - Taxonomy tags have abnormal spacing in highlighted mode
  assets/css/blocks/post.css
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/post/style.scss
  src/blocks/post/styling.js
Labels: bug, needs review

#1581 SPCTR-837 : Content Timeline Block - Fix default text alignment for right-oriented content timeline block
  assets/css/blocks/timeline.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/content-timeline/render.js
  dist/style-blocks.css
  includes/blocks/content-timeline/frontend.css.php
  includes/blocks/post-timeline/frontend.css.php
  src/blocks/timeline/content-timeline/editor.lazy.scss
  src/blocks/timeline/content-timeline/styling.js
  src/blocks/timeline/inline-styles.js
  src/blocks/timeline/style.scss
Labels: bug, needs review, css

#1609 Border Components - Remove unnecessary conditions for handling default attributes
  blocks-config/uagb-controls/generateAttributes.js
  blocks-config/uagb-controls/generateBorderCSS.js
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/wp-search/attributes.php
  src/blocks/wp-search/attributes.js
Labels: enhancement

#1606 SPCTR-859 Advanced Heading: Sub-Heading/Paragraph Bottom Margin Issue
  assets/css/blocks/advanced-heading.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/advanced-heading/style.scss
Labels: bug, needs review, css

#1604 SPCTR-860 Forms Block - Toggle to turn ON/OFF labels
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/form/settings.js
  includes/blocks/forms/attributes.php
  includes/blocks/forms/frontend.css.php
  src/blocks/forms/attributes.js
  src/blocks/forms/settings.js
  src/blocks/forms/styling.js
Labels: enhancement, php, javascript, needs review

#1613 SPCTR-864 Container Block: Responsive Spacing UNITS
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/container/settings.js
  includes/blocks/container/attributes.php
  includes/blocks/container/frontend.css.php
  src/blocks/container/attributes.js
  src/blocks/container/settings.js
  src/blocks/container/styling.js
Labels: bug, enhancement, php, javascript

#1578 SPCTR-783 FAQ Block label change for icon
  dist/chunks/faq/settings.js
  src/blocks/faq/settings.js
Labels: javascript, needs review

#1608 Update: Image Block - Replace old border with new Responsive Border
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/advanced-heading/settings.js
  dist/chunks/blockquote/settings.js
  dist/chunks/buttons-child/settings.js
  dist/chunks/buttons/settings.js
  dist/chunks/call-to-action/settings.js
  dist/chunks/cf7-styler/settings.js
  dist/chunks/content-timeline/settings.js
  dist/chunks/faq/settings.js
  dist/chunks/form/settings.js
  dist/chunks/gf-styler/settings.js
  dist/chunks/how-to/settings.js
  dist/chunks/how-to/step-settings.js
  dist/chunks/icon-list/settings.js
  dist/chunks/image/settings.js
  dist/chunks/info-box/render.js
  dist/chunks/info-box/settings.js
  dist/chunks/inline-notice/settings.js
  dist/chunks/marketing-button/settings.js
  dist/chunks/post-carousel/render.js
  dist/chunks/post-grid/render.js
  dist/chunks/post-grid/settings.js
  dist/chunks/post-masonry/render.js
  dist/chunks/post-timeline/settings.js
  dist/chunks/price-list-child/render.js
  dist/chunks/price-list/settings.js
  dist/chunks/review/settings.js
  dist/chunks/star-rating/settings.js
  dist/chunks/table-of-contents/settings.js
  dist/chunks/tabs/settings.js
  dist/chunks/taxonomy-list/settings.js
  dist/chunks/team/settings.js
  dist/chunks/testimonial/settings.js
  dist/chunks/wp-search/settings.js
  dist/vendors~chunks/post-masonry/react-masonry-component.js
  includes/blocks/image/attributes.php
  includes/blocks/image/frontend.css.php
  src/blocks/image/attributes.js
  src/blocks/image/settings.js
  src/blocks/image/styling.js
Labels: enhancement

#1620 Feat: Responsive Border for Table of Content
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/advanced-heading/settings.js
  dist/chunks/blockquote/settings.js
  dist/chunks/buttons-child/settings.js
  dist/chunks/buttons/settings.js
  dist/chunks/call-to-action/settings.js
  dist/chunks/cf7-styler/settings.js
  dist/chunks/column/settings.js
  dist/chunks/columns/settings.js
  dist/chunks/container/settings.js
  dist/chunks/content-timeline-child/render.js
  dist/chunks/content-timeline/settings.js
  dist/chunks/faq/settings.js
  dist/chunks/form/settings.js
  dist/chunks/gf-styler/settings.js
  dist/chunks/how-to/settings.js
  dist/chunks/how-to/step-settings.js
  dist/chunks/icon-list/settings.js
  dist/chunks/image/settings.js
  dist/chunks/info-box/settings.js
  dist/chunks/inline-notice/settings.js
  dist/chunks/lottie/settings.js
  dist/chunks/marketing-button/settings.js
  dist/chunks/post-grid/settings.js
  dist/chunks/post-timeline/render.js
  dist/chunks/post-timeline/settings.js
  dist/chunks/price-list/settings.js
  dist/chunks/review/settings.js
  dist/chunks/section/settings.js
  dist/chunks/social-share/settings.js
  dist/chunks/star-rating/settings.js
  dist/chunks/table-of-contents/settings.js
  dist/chunks/tabs/settings.js
  dist/chunks/taxonomy-list/settings.js
  dist/chunks/team/settings.js
  dist/chunks/testimonial/settings.js
  dist/chunks/wp-search/settings.js
  dist/vendors~chunks/post-masonry/react-masonry-component.js
  includes/blocks/table-of-contents/attributes.php
  includes/blocks/table-of-contents/frontend.css.php
  src/blocks/table-of-contents/attributes.js
  src/blocks/table-of-contents/edit.js
  src/blocks/table-of-contents/settings.js
  src/blocks/table-of-contents/styling.js
Labels: enhancement

#1597 SPCTR-880 Fix: Container block padding,margin values are not inherited to mobile from Tablet
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/styling.js
Labels: bug
