Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2022-06, with the labels that each got.

#1622 SPCTR-928 - Fix: Updated Full-Width Alignment Icon
  blocks-config/uagb-controls/renderIcon.js
  dist/blocks.asset.php
  dist/blocks.js
Labels: enhancement

#1641 SPCTR-1013 Call to Action- When Layout is set to Stack on None, Gap Between Buttons does not work in the editor.
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/call-to-action/inline-styles.js
Labels: bug, needs review

#1642 SPCTR-1011 Blockquote: Author image gap is initially visible even when author image is not set
  dist/chunks/blockquote/settings.js
  src/blocks/blockquote/settings.js
Labels: bug, needs review

#1635 SPCTR-867 Testimonial Block: Arrows do not work in WP editor
  dist/chunks/testimonial/render.js
  src/blocks/testimonial/render.js
Labels: bug, needs review

#1643 SPCTR-876 Using only CSS instead of JS calculations for container padding
  assets/js/container.js
  includes/blocks/container/block.php
  includes/blocks/container/frontend.css.php
  includes/blocks/container/frontend.js.php
Labels: bug

#1628 SPCTR-907 - CTA Block Focus Effects in WP Editor
  dist/chunks/call-to-action/render.js
  src/blocks/call-to-action/editor.lazy.scss
Labels: enhancement, needs review

#1657 SPCTR-909 - Update: TOC Block -Added decimal point option
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/table-of-contents/settings.js
  includes/blocks/table-of-contents/attributes.php
  includes/blocks/table-of-contents/frontend.css.php
  src/blocks/table-of-contents/attributes.js
  src/blocks/table-of-contents/settings.js
  src/blocks/table-of-contents/styling.js
Labels: enhancement

#1645 SPCTR-881 - Update: Added Star rating block alignment Control
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/star-rating/settings.js
  includes/blocks/star-rating/attributes.php
  includes/blocks/star-rating/frontend.css.php
  src/blocks/star-rating/attributes.js
  src/blocks/star-rating/settings.js
  src/blocks/star-rating/styling.js
Labels: enhancement

#1614 SPCTR-850 CTA Block: Removed Left Content Spacing from Spacing Settings
  assets/css/blocks/call-to-action.css
  assets/js/cross-site-cp-helper.min.js
  assets/js/forms.min.js
  assets/js/table-of-contents.min.js
  assets/js/timeline.min.js
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/chunks/call-to-action/settings.js
  dist/chunks/info-box/render.js
  dist/chunks/info-box/settings.js
  dist/style-blocks.css
  includes/blocks/call-to-action/attributes.php
  includes/blocks/call-to-action/frontend.css.php
  src/blocks/call-to-action/attributes.js
  src/blocks/call-to-action/edit.js
  src/blocks/call-to-action/inline-styles.js
  src/blocks/call-to-action/settings.js
  src/blocks/call-to-action/style.scss
Labels: php, javascript, needs review

#1677 SPCTR-970 - Update: Social Share Block - Added global color control
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/social-share/settings.js
  includes/blocks/social-share-child/attributes.php
  includes/blocks/social-share/attributes.php
  includes/blocks/social-share/frontend.css.php
  src/blocks/social-share-child/attributes.js
  src/blocks/social-share/attributes.js
  src/blocks/social-share/settings.js
  src/blocks/social-share/styling.js
Labels: enhancement

#1634 SPCTR-900 - Update: Added Icon list block global color control
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/icon-list/settings.js
  includes/blocks/icon-list/attributes.php
  includes/blocks/icon-list/frontend.css.php
  src/blocks/icon-list-child/attributes.js
  src/blocks/icon-list/attributes.js
  src/blocks/icon-list/settings.js
  src/blocks/icon-list/styling.js
Labels: enhancement

#1701 SPCTR-954 - Update: Added Icon list responsive alignment and responsive Layout
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/icon-list/settings.js
  includes/blocks/faq/attributes.php
  includes/blocks/faq/frontend.css.php
  includes/blocks/icon-list/attributes.php
  includes/blocks/icon-list/frontend.css.php
  includes/blocks/info-box/frontend.css.php
  src/blocks/icon-list/attributes.js
  src/blocks/icon-list/settings.js
  src/blocks/icon-list/styling.js
Labels: enhancement

#1676 SPCTR-959 - Fix:Image Block - if disable caption then caption style panel hide not working issue
  dist/chunks/image/settings.js
  src/blocks/image/settings.js
Labels: bug

#1709 SPCTR-367 Testimonials Block - Increased maximum limit for Autoplay Speed
  dist/chunks/testimonial/settings.js
  src/blocks/testimonial/settings.js
Labels: enhancement, needs review

#1713 SPCTR-813 - Fix: Image Block - image size not working properly issue fixing
  dist/chunks/image/settings.js
  src/blocks/image/settings.js
Labels: bug

#1666 SPCTR-978 - Fix: Range Fallback - Buttons
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/advanced-heading/settings.js
  dist/chunks/blockquote/settings.js
  dist/chunks/buttons-child/settings.js
  dist/chunks/buttons/settings.js
  dist/chunks/call-to-action/settings.js
  dist/chunks/cf7-styler/settings.js
  dist/chunks/content-timeline/settings.js
  dist/chunks/faq/settings.js
  dist/chunks/form/settings.js
  dist/chunks/gf-styler/settings.js
  dist/chunks/how-to/settings.js
  dist/chunks/how-to/step-settings.js
  dist/chunks/icon-list/settings.js
  dist/chunks/image/settings.js
  dist/chunks/info-box/render.js
  dist/chunks/info-box/settings.js
  dist/chunks/inline-notice/settings.js
  dist/chunks/marketing-button/settings.js
  dist/chunks/post-carousel/settings.js
  dist/chunks/post-grid/settings.js
  dist/chunks/post-masonry/settings.js
  dist/chunks/post-timeline/render.js
  dist/chunks/post-timeline/settings.js
  dist/chunks/price-list-child/render.js
  dist/chunks/price-list/render.js
  dist/chunks/price-list/settings.js
  dist/chunks/review/settings.js
  dist/chunks/social-share/settings.js
  dist/chunks/star-rating/settings.js
  dist/chunks/table-of-contents/settings.js
  dist/chunks/tabs/settings.js
  dist/chunks/taxonomy-list/settings.js
  dist/chunks/team/settings.js
  dist/chunks/testimonial/settings.js
  dist/chunks/wp-search/settings.js
  dist/vendors~chunks/buttons-child/settings~chunks/call-to-action/settings~chunks/content-timeline/setting~3f23f369.js
  dist/vendors~chunks/post-masonry/react-masonry-component.js
  includes/blocks/buttons-child/attributes.php
  includes/blocks/buttons/attributes.php
  includes/blocks/buttons/frontend.css.php
  src/blocks/buttons-child/attributes.js
  src/blocks/buttons-child/styling.js
  src/blocks/buttons/attributes.js
  src/blocks/buttons/styling.js
Labels: enhancement

#1668 SPCTR-982 - Fix: Range Fallback - Container
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/call-to-action/render.js
  dist/chunks/call-to-action/settings.js
  dist/chunks/faq/settings.js
  dist/chunks/form/settings.js
  dist/chunks/icon-list/settings.js
  dist/chunks/marketing-button/settings.js
  dist/chunks/price-list/settings.js
  dist/chunks/tabs/settings.js
  dist/chunks/team/settings.js
  dist/vendors~chunks/buttons-child/settings~chunks/call-to-action/settings~chunks/content-timeline/setting~3f23f369.js
  includes/blocks/container/frontend.css.php
  src/blocks/container/styling.js
Labels: enhancement

#1633 SPCTR-976 - Fix: Range Fallback - Advanced Heading
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/advanced-heading/settings.js
  dist/chunks/blockquote/settings.js
  dist/chunks/buttons-child/settings.js
  dist/chunks/buttons/settings.js
  dist/chunks/call-to-action/settings.js
  dist/chunks/cf7-styler/settings.js
  dist/chunks/column/settings.js
  dist/chunks/columns/settings.js
  dist/chunks/container/settings.js
  dist/chunks/content-timeline/settings.js
  dist/chunks/faq/settings.js
  dist/chunks/form/settings.js
  dist/chunks/form/textarea-settings.js
  dist/chunks/form/toggle-settings.js
  dist/chunks/gf-styler/settings.js
  dist/chunks/google-map/render.js
  dist/chunks/google-map/settings.js
  dist/chunks/how-to/settings.js
  dist/chunks/icon-list-child/settings.js
  dist/chunks/icon-list/settings.js
  dist/chunks/image/settings.js
  dist/chunks/info-box/settings.js
  dist/chunks/inline-notice/settings.js
  dist/chunks/lottie/settings.js
  dist/chunks/marketing-button/settings.js
  dist/chunks/post-grid/settings.js
  dist/chunks/post-timeline/settings.js
  dist/chunks/price-list/settings.js
  dist/chunks/review/settings.js
  dist/chunks/section/settings.js
  dist/chunks/social-share-child/settings.js
  dist/chunks/social-share/settings.js
  dist/chunks/star-rating/settings.js
  dist/chunks/table-of-contents/settings.js
  dist/chunks/tabs/settings.js
  dist/chunks/taxonomy-list/settings.js
  dist/chunks/team/settings.js
  dist/chunks/testimonial/settings.js
  dist/chunks/wp-search/settings.js
  includes/blocks/advanced-heading/attributes.php
  includes/blocks/advanced-heading/frontend.css.php
  src/blocks/advanced-heading/styling.js
Labels: enhancement

#1694 SPCTR-998 - Fix: Range Fallback - Social Share
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/social-share/attributes.php
  includes/blocks/social-share/frontend.css.php
  src/blocks/social-share/attributes.js
  src/blocks/social-share/styling.js
Labels: enhancement

#1693 SPCTR-999 Fix: Range Fallback - Star Rating
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/star-rating/attributes.php
  includes/blocks/star-rating/frontend.css.php
  src/blocks/star-rating/attributes.js
  src/blocks/star-rating/styling.js
Labels: enhancement

#1667 SPCTR-979 - Fix: Range Fallback - Call to Action
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/advanced-heading/render.js
  dist/chunks/blockquote/render.js
  dist/chunks/buttons-child/render.js
  dist/chunks/buttons/render.js
  dist/chunks/buttons/settings.js
  dist/chunks/call-to-action/render.js
  dist/chunks/call-to-action/settings.js
  dist/chunks/cf7-styler/render.js
  dist/chunks/column/render.js
  dist/chunks/column/settings.js
  dist/chunks/columns/render.js
  dist/chunks/columns/settings.js
  dist/chunks/container/settings.js
  dist/chunks/content-timeline/render.js
  dist/chunks/faq/render.js
  dist/chunks/form/render.js
  dist/chunks/form/textarea-render.js
  dist/chunks/gf-styler/render.js
  dist/chunks/google-map/render.js
  dist/chunks/how-to/render.js
  dist/chunks/how-to/step-render.js
  dist/chunks/icon-list/render.js
  dist/chunks/image/render.js
  dist/chunks/image/settings.js
  dist/chunks/info-box/render.js
  dist/chunks/inline-notice/render.js
  dist/chunks/marketing-button/render.js
  dist/chunks/post-carousel/render.js
  dist/chunks/post-grid/blog.js
  dist/chunks/post-masonry/react-masonry-component.js
  dist/chunks/post-timeline/render.js
  dist/chunks/price-list/render.js
  dist/chunks/review/render.js
  dist/chunks/section/render.js
  dist/chunks/section/settings.js
  dist/chunks/social-share/render.js
  dist/chunks/star-rating/render.js
  dist/chunks/table-of-contents/render.js
  dist/chunks/tabs/render.js
  dist/chunks/tabs/settings.js
  dist/chunks/taxonomy-list/render.js
  dist/chunks/team/render.js
  dist/chunks/testimonial/render.js
  dist/chunks/testimonial/settings.js
  dist/chunks/wp-search/render.js
  includes/blocks/call-to-action/attributes.php
  includes/blocks/call-to-action/frontend.css.php
  src/blocks/call-to-action/attributes.js
  src/blocks/call-to-action/inline-styles.js
Labels: enhancement

#1698 SPCTR-991 - Fix: Range Fallback - Inline Notice
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/inline-notice/frontend.css.php
  includes/blocks/inline-notice/frontend.js.php
  src/blocks/inline-notice/settings.js
  src/blocks/inline-notice/styling.js
Labels: enhancement

#1691 SPCTR-1001: Range Fallback - Tabs
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/tabs/frontend.css.php
  src/blocks/tabs/attributes.js
  src/blocks/tabs/styling.js
Labels: enhancement

#1696 SPCTR-993 - Fix: Range Fallback - Marketing Button
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/marketing-button/attributes.php
  includes/blocks/marketing-button/frontend.css.php
  src/blocks/marketing-button/styling.js
Labels: enhancement

#1692 SPCTR-1000 Fix: Range Fallback - Table of Contents
  blocks-config/table-of-content/class-uagb-table-of-content.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/table-of-contents/render.js
  includes/blocks/table-of-contents/frontend.css.php
  src/blocks/table-of-contents/render.js
  src/blocks/table-of-contents/styling.js
Labels: enhancement

#1711 SPCTR-1062 - Fix: Astra theme border control automatic comes inside image block
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/image/block.js
Labels: bug

#1697 SPCTR-992 - Fix: Range Fallback - Lottie
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/lottie/render.js
  includes/blocks/lottie/frontend.js.php
  src/blocks/lottie/render.js
  src/blocks/lottie/styling.js
Labels: enhancement

#1664 SPCTR-977 - Fix: Range Fallback - Blockquote
  classes/class-uagb-block-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/blockquote/frontend.css.php
  src/blocks/blockquote/styling.js
Labels: enhancement

#1646 SPCTR-1002 - Fix: Range Fallback - Taxonomy List
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/taxonomy-list/attributes.php
  includes/blocks/taxonomy-list/frontend.css.php
  src/blocks/taxonomy-list/attributes.js
  src/blocks/taxonomy-list/styling.js
Labels: enhancement

#1687 SPCTR-1006 - Fix: Range Fallback - WP Search
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/wp-search/attributes.php
  includes/blocks/wp-search/frontend.css.php
  src/blocks/wp-search/attributes.js
  src/blocks/wp-search/styling.js
Labels: enhancement

#1690 SPCTR-1003 - Fix: Range Fallback - Team
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/team/attributes.php
  includes/blocks/team/frontend.css.php
  src/blocks/team/attributes.js
  src/blocks/team/styling.js
Labels: enhancement

#1695 SPCTR-994 - Fix: Range Fallback - Post Blocks
  blocks-config/post-timeline/class-uagb-post-timeline.php
  blocks-config/post/class-uagb-post.php
  classes/class-uagb-block-helper.php
  classes/class-uagb-helper.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/post-carousel/render.js
  dist/chunks/post-grid/blog.js
  dist/chunks/post-grid/render.js
  dist/chunks/post-masonry/react-masonry-component.js
  dist/chunks/post-masonry/render.js
  includes/blocks/post-carousel/attributes.php
  includes/blocks/post-carousel/frontend.css.php
  includes/blocks/post-grid/attributes.php
  includes/blocks/post-grid/frontend.css.php
  includes/blocks/post-masonry/attributes.php
  includes/blocks/post-masonry/frontend.css.php
  includes/blocks/post-timeline/attributes.php
  src/blocks/post/post-carousel/attributes.js
  src/blocks/post/post-carousel/blog.js
  src/blocks/post/post-carousel/edit.js
  src/blocks/post/post-carousel/render.js
  src/blocks/post/post-excerpt/edit.js
  src/blocks/post/post-grid/attributes.js
  src/blocks/post/post-grid/blog.js
  src/blocks/post/post-grid/edit.js
  src/blocks/post/post-grid/render.js
  src/blocks/post/post-masonry/attributes.js
  src/blocks/post/post-masonry/blog.js
  src/blocks/post/post-masonry/edit.js
  src/blocks/post/post-masonry/render.js
  src/blocks/post/styling.js
  src/blocks/timeline/post-timeline/attributes.js
Labels: enhancement

#1740 Fixed Testimonials Warnings - Defined rowGap and columnGap responsive attributes in php
  includes/blocks/testimonial/attributes.php
Labels: php, needs review

#1737 SPCTR-1118 - info box icon size issue inside frontend
  assets/css/blocks/info-box.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/info-box/style.scss
Labels: bug

#1717 SPCTR-599 - Image Block - Responsive Sizing Issues
  dist/chunks/image/render.js
  dist/chunks/image/settings.js
  src/blocks/image/image.js
  src/blocks/image/settings.js
  src/components/image-size-control/index.js
Labels: bug, javascript, needs review

#1751 SPCTR-1105 Container - Added left and right spacing for root container in Editor (Desktop)
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/editor.lazy.scss
Labels: needs review, css

#1746 SPCTR-1144 Container - Box Shadow Hover Bug
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/container/frontend.css.php
  src/blocks/container/styling.js
Labels: php, javascript, needs review

#1728 SPCTR-1081 - Improvement: Heading block - replace multi button with tabs
  dist/chunks/advanced-heading/settings.js
  src/blocks/advanced-heading/settings.js
Labels: enhancement

#1734 SPCTR-1119 - Fix: Info Box icon copy/paste style issue
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/info-box/attributes.js
Labels: bug

#1748 SPCTR-1159 - Fix: Heading block highlight border zero not working issue
  assets/css/blocks/advanced-heading.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/advanced-heading/style.scss
Labels: bug

#1753 Button Block - Fix button text break issue inside editor
  assets/css/blocks/buttons.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/buttons/style.scss
Labels: bug

#1744 SPCTR-1165 - Fix: Image Block caption styling option not showing if set layout as an …
  dist/chunks/image/settings.js
  src/blocks/image/settings.js
Labels: bug

#1719 SPCTR-1007 - Phone default code not working properly for USA and Canada
  dist/blocks-placeholder.js
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/forms/child-blocks/phone/country-option.js
Labels: bug, javascript, needs review

#1771 SPCTR-1016 Update checkbox and radio default size to 10px for cf7 designer block
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/cf7-designer/attributes.js
Labels: enhancement

#1764 SPCTR-1179 SPCTR-1112 SPCTR-1061 Added Fonts: DM Sans, DM Serif Display, Unna
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  blocks-config/uagb-controls/fonts.js
  dist/blocks.asset.php
  dist/blocks.js
Labels: needs review

#1765 SPCTR-1188 - Infobox: CTA Text has underline on frontend
  assets/css/blocks/info-box.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/info-box/frontend.css.php
  src/blocks/info-box/style.scss
  src/blocks/info-box/styling.js
Labels: javascript, css

#1768 SPCTR-1182 - Feat: Inline Multi-button
  blocks-config/uagb-controls/block-icons.js
  dist/blocks.asset.php
  dist/blocks.js
  dist/chunks/column/settings.js
  dist/chunks/columns/settings.js
  dist/chunks/container/settings.js
  dist/chunks/section/settings.js
  dist/chunks/testimonial/settings.js
  dist/common-editor.css
  includes/blocks/container/attributes.php
  src/blocks/column/attributes.js
  src/blocks/columns/attributes.js
  src/blocks/container/attributes.js
  src/blocks/section/attributes.js
  src/blocks/testimonial/attributes.js
  src/components/background/editor.lazy.scss
  src/components/background/index.js
  src/components/multi-buttons-control/editor.lazy.scss
  src/components/multi-buttons-control/index.js
  src/components/select-control/editor.lazy.scss
  src/styles/control-header.scss
Labels: enhancement

#1773 SPCTR-1186 - Social Share - In Style section all the tabs are open
  dist/chunks/social-share/settings.js
  src/blocks/social-share/settings.js
Labels: bug, javascript, needs review

#1774 SPCTR-1192 - Social Share Child Blocks - Disable Hyperlink Click Events for Editor
  dist/chunks/social-share-child/render.js
  src/blocks/social-share-child/editor.lazy.scss
Labels: bug, needs review, css
