Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2022-09, with the labels that each got.

#2233 SPCTR-1738 Responsive and Display Condition - Added responsive and display condition for core block again.
  README.md
  admin-core/inc/admin-helper.php
  classes/class-uagb-helper.php
  classes/class-uagb-init-blocks.php
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  readme.txt
  src/blocks/extensions/advanced-settings/index.js
  src/blocks/extensions/attributes.js
  src/blocks/extensions/block.js
  src/blocks/extensions/condition-block/index.js
Labels: create zip

#2250 SPCTR-1761 - Fix: Media Picker Icon Colors
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/common-editor.css
  dist/style-blocks.css
  readme.txt
  src/components/image/index.js
  src/styles/control-media-picker.scss
Labels: javascript, css

#2242 SPCTR-1725 Info Box Title, Description, Separator - Fixed margin specificity issues for frontend
  README.md
  includes/blocks/info-box/frontend.css.php
  readme.txt
Labels: bug, php, frontend

#2262 SPCTR-1765 - Fix: Media Picker Optional Labels
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/blockquote/settings.js
  src/blocks/how-to/child-blocks/step/settings.js
  src/blocks/how-to/settings.js
  src/blocks/icon-list-child/settings.js
  src/blocks/image/settings.js
  src/blocks/info-box/settings.js
  src/blocks/lottie/settings.js
  src/blocks/price-list-child/settings.js
  src/blocks/review/settings.js
  src/blocks/social-share-child/settings.js
  src/blocks/team/settings.js
  src/blocks/testimonial/settings.js
  src/components/background/index.js
  src/components/image/index.js
  src/components/responsive-image/index.js
Labels: javascript

#2273 SPCTR-1734 Table of Contents - Collapse feature not working in the editor
  README.md
  assets/js/table-of-contents.js
  assets/js/table-of-contents.min.js
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/table-of-contents/render.js
Labels: bug, javascript

#2292 SPCTR-1814 Forms - Checkbox Field - 'Required' Toggle was not clickable
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/forms/child-blocks/checkbox/render.js
Labels: bug, javascript

#2294 SPCTR-1816: Fixed Zero Rendering for Border Width and Radius
  README.md
  classes/class-uagb-block-helper.php
  readme.txt
Labels: php, frontend

#2283 SPCTR-1803 Price List - Removed default top and bottom padding for image due to misaligned look in editor
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/restaurant-menu/attributes.php
  readme.txt
  src/blocks/price-list/attributes.js
  src/blocks/price-list/presets.js
Labels: bug, php, javascript

#2286 SPCTR-1800 Content Timeline - Default description change
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/timeline/content-timeline-child/attributes.js
  src/blocks/timeline/content-timeline-child/deprecated.js
  src/blocks/timeline/content-timeline/attributes.js
Labels: javascript, ux

#2291 SPCTR-1811 Forms - Added 'Required' toggle for Accept field
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/forms/child-blocks/accept/editor.lazy.scss
  src/blocks/forms/child-blocks/accept/render.js
Labels: enhancement, ux

#2279 SPCTR-1793 Info Box - Images seem enlarged after old users upgrade to Spectra
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/info-box/attributes.php
  readme.txt
  src/blocks/info-box/attributes.js
Labels: bug, php, javascript

#2287 SPCTR-1802 Content Timeline - Removed extra margin added to title and description by theme and core WordPress in editor and frontend.
  README.md
  assets/css/blocks/timeline.css
  dist/blocks.style.css
  dist/style-blocks.css
  readme.txt
  src/blocks/timeline/style.scss
Labels: bug, css

#2277 SPCTR-1792 - Improvement: Updated Video Icon
  README.md
  blocks-config/uagb-controls/block-icons.js
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/components/image/index.js
Labels: javascript

#2300 SPCTR-1825 Forms Toggle - Changed default label to 'Toggle' (previously 'Name')
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/forms/child-blocks/toggle/attributes.js
  src/blocks/forms/child-blocks/toggle/deprecated.js
Labels: bug, ux

#2247 SPCTR-1740 - Fix: Call To Action Block button css conflict with newspaper theme
  README.md
  classes/class-uagb-block-helper.php
  includes/blocks/call-to-action/frontend.css.php
  includes/blocks/info-box/frontend.css.php
  includes/blocks/marketing-button/frontend.css.php
  readme.txt
Labels: bug

#2330 SPCTR-1890 Info Box - Remove default image width for new users only
  README.md
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/info-box/attributes.php
  readme.txt
  src/blocks/info-box/attributes.js
Labels: bug, php, javascript
