Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2023-05, with the labels that each got.

#3077 Improvement: Global - Added Common Variation Picker UI
  dist/common-editor.css
  src/common-editor.scss
  src/styles/_variables.scss
  src/styles/control-variation-picker.scss
Labels: dependencies, ready-to-merge, css, editor

#3081 SPCTR-2803 Counter: Uncaught error in console when used as an innerblock in Countdown
  assets/js/spectra-counter.js
  assets/js/spectra-counter.min.js
Labels: bug

#3049 SPCTR-2745-Fix image gallery carousel not loading properly on page load
  README.md
  blocks-config/image-gallery/class-spectra-image-gallery.php
  includes/blocks/image-gallery/frontend.css.php
  readme.txt
Labels: bug

#3091 SPCTR-2811 Post Blocks - Fixed uncaught console error, especially whe…
  assets/js/post.js
  assets/js/post.min.js
Labels: bug

#3089 SPCTR-2810 Counter: Some Counters on page/post aren't initialized when using Edge browser on Windows
  .eslintrc.js
  assets/js/spectra-counter.js
  assets/js/spectra-counter.min.js
Labels: bug

#2986 Fix:SPCTR-2553-Table of content - not properly shown in preview of post when used as a custom layout inside post/page content.
  README.md
  classes/class-uagb-post-assets.php
  readme.txt
Labels: bug, php

#3032 Fix:SPCTR-2648-Custom CSS loading issue on frontend of WP core block when spectra block is not present on page
  README.md
  classes/class-uagb-post-assets.php
  readme.txt
Labels: bug, php

#3093 Fix:SPCTR-2807-[TOC] Gap Between Lists not working in front-end
  README.md
  includes/blocks/table-of-contents/frontend.css.php
  readme.txt
Labels: bug

#3120 SPCTR-2840 - Changelog: Spectra v2.6.0
  README.md
  blocks-config/popup-builder/class-uagb-popup-builder.php
  classes/class-uagb-init-blocks.php
  classes/class-uagb-update.php
  includes/blocks/popup-builder/attributes.php
  includes/blocks/popup-builder/block.php
  includes/blocks/popup-builder/frontend.css.php
  includes/blocks/popup-builder/frontend.js.php
  languages/ultimate-addons-for-gutenberg.pot
  readme.txt
Labels: ready-to-merge

#3132 SPCTR-2849: Added Semicolor to Avoid Multiple Block Breaking Issue
  blocks-config/image-gallery/class-spectra-image-gallery.php
Labels: ready-to-merge, php, frontend

#3136 SPCTR-2854 - Fix: Table Of Contents - Responsive Gap Between List Items Not Working on the Front-end
  includes/blocks/table-of-contents/frontend.css.php
Labels: ready-to-merge, php, frontend

#3141 SPCTR-2863 - Fix: Popup Builder - Info Bar Displays as Banner in the Admin Dashboard.
  blocks-config/popup-builder/class-uagb-popup-builder.php
Labels: bug, ready-to-merge, php, admin, ux

#3145 SPCTR-2864 Taxonomy List - Heading adds margin at top on frontend
  assets/css/blocks/taxonomy-list.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/taxonomy-list/style.scss
Labels: bug

#3146 SPCTR-2872 UAGLinkControl - Title goes out of viewport fix
  src/components/link-control/editor.lazy.scss
Labels: bug

#3147 SPCTR-2876 - Fix: Active Modal Page Scrollable on the Front-end.
  assets/js/modal.js
  assets/js/modal.min.js
Labels: bug, javascript, editor, frontend

#3160 Added Changelog Entry for Image Gallery Fix
  README.md
  readme.txt
Labels: ready-to-merge

#3159 SPCTR-2895: Replaced Pro Links with Coming Soon
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/pages/blocks/BlockCard.js
  admin-core/assets/src/dashboard-app/pages/blocks/DynamicContentExtension.js
Labels: ready-to-merge, javascript, admin

#3166 Admin Dashboard / Animations - Activate all and Deactivate all buttons have no impact on Animations status; Also fixed missing i18n
  README.md
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/pages/blocks/FilterTabs.js
  readme.txt
Labels: bug, javascript, ux, i18n, admin dashboard

#3181 SPCTR-2897 - Fix: Image Gallery - Front-end Glitching for Masonry Layout.
  README.md
  blocks-config/image-gallery/class-spectra-image-gallery.php
  includes/blocks/image-gallery/frontend.css.php
  readme.txt
Labels: bug, php, frontend

#3186 Fix:SPCTR-2903- Call To Action - When using call to action with additional button, on responsive view button is getting more height
  README.md
  includes/blocks/call-to-action/attributes.php
  readme.txt
Labels: bug

#3182 Fix:SPCTR-2885-Post carousel -arrow not visible in FSE template
  README.md
  assets/css/blocks/post.css
  dist/blocks.style.css
  dist/style-blocks.css
  readme.txt
  src/blocks/post/style.scss
Labels: bug

#3202 Updated Token Generator Path to Avoid Document URL Clashing
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUsers.js
Labels: bug, ready-to-merge, javascript, admin
