Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2023-01, with the labels that each got.

#2598 Add Minimum Height option for slider
  assets/css/blocks/slider.css
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/slider/attributes.php
  includes/blocks/slider/frontend.css.php
  src/blocks/slider/attributes.js
  src/blocks/slider/editor.lazy.scss
  src/blocks/slider/render.js
  src/blocks/slider/settings.js
  src/blocks/slider/style.scss
  src/blocks/slider/styling.js
Labels: enhancement

#2599 Added Swiper JS Dependencies
  assets/css/swiper-bundle.min.css
  assets/js/swiper-bundle.min.js
  classes/class-uagb-block-module.php
  package-lock.json
  package.json
Labels: dependencies

#2589 SPCTR-2222 Spectra Text Control: Added support for 'type' prop
  dist/blocks.asset.php
  dist/blocks.js
  src/components/text-control/index.js
Labels: enhancement

#2615 Fix: Console warning on front end for slider library script
  assets/js/swiper-bundle.min.js
Labels: bug

#2610 SPCTR-2165 - Fix: Admin Pro Improvements
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/images/dashboard-uag-logo.svg
  admin-core/assets/src/common/tailwind-important.scss
  admin-core/assets/src/dashboard-app/MainNav.js
  admin-core/assets/src/dashboard-app/PluginStats.js
  admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
  admin-core/assets/src/dashboard-app/pages/blocks/BlockCard.js
  admin-core/assets/src/dashboard-app/pages/blocks/Blocks.js
  admin-core/assets/src/dashboard-app/pages/settings/BlockSettings.js
  admin-core/assets/src/dashboard-app/pages/settings/Settings.js
  admin-core/assets/src/dashboard-app/pages/settings/block-settings/Login.js
Labels: javascript, admin

#2614 SPCTR-2207 Countdown: Added dynamic defaults for endDateTime
  assets/js/uagb-countdown.js
  assets/js/uagb-countdown.min.js
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/countdown/attributes.js
  src/blocks/countdown/edit.js
Labels: enhancement

#2635 SPCTR-2260 - Fix: Instagram Api Improvements
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
  admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUsers.js
  admin-core/inc/admin-menu.php
  classes/class-uagb-admin-helper.php
Labels: ready-to-merge, php, javascript, admin, editor
