Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2023-07, with the labels that each got.

#3323 SPCTR-3089: Added Show In Menu for Popup Builder
  classes/class-uagb-init-blocks.php
Labels: php, admin, frontend

#3251 SPCTR-2574 - New: Common NavBar Structure
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/DashboardApp.js
  admin-core/assets/src/common/components/AdminHeader.js
  admin-core/assets/src/common/components/ChangeLogPopup.js
  admin-core/assets/src/common/components/PluginStats.js
  admin-core/assets/src/dashboard-app/MainNav.js
  admin-core/assets/src/dashboard-app/SettingsRoute.js
  admin-core/assets/src/dashboard-app/SettingsWrap.js
  admin-core/inc/admin-menu.php
  admin-core/tailwind.config.js
  admin-core/webpack.config.js
Labels: enhancement, php, javascript, css, admin, ux

#3329 Spectra 2.7.0 changelog
  README.md
  readme.txt
Labels: ready-to-merge

#3311 SPCTR-3014: Fix - Separator mobile width issue in frontend
  README.md
  assets/css/blocks/separator.css
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/separator/frontend.css.php
  readme.txt
  src/blocks/separator/style.scss
Labels: bug

#3366 Version-bump-v2.7.2
  README.md
  classes/class-uagb-loader.php
  classes/class-uagb-update.php
  languages/ultimate-addons-for-gutenberg.pot
  package-lock.json
  package.json
  readme.txt
  ultimate-addons-for-gutenberg.php
Labels: Release PR
