Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2023-04, with the labels that each got.

#2924 Fix: PHP Explode Parameter Two Handlers
  classes/class-uagb-block-helper.php
  lib/uagb-webfont/uagb-webfont-loader.php
Labels: bug, ready-to-merge, php, frontend

#2927 Imrpovement: Updated Admin Pro Dependencies
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/PluginStats.js
  admin-core/assets/src/dashboard-app/pages/blocks/BlockCard.js
  admin-core/assets/src/dashboard-app/pages/blocks/Extensions.js
  admin-core/assets/src/dashboard-app/pages/blocks/FilterTabs.js
Labels: dependencies, ready-to-merge, javascript, admin

#2928 SPCTR-2572 Countdown - Countdown not working in Slider block when the Slider is set to infinite loop (on Frontend)
  assets/js/uagb-countdown.js
  assets/js/uagb-countdown.min.js
Labels: bug

#2967 SPCTR-2579: Fix: Global: Scrollbar in x-axis of sidebar when switched to RTL
  README.md
  dist/common-editor.css
  readme.txt
  src/common-editor.scss
Labels: css

#2922 Fix:SPCTR-2551- Post carousel - Gap between post not visible when only 2 post is present.
  README.md
  blocks-config/post/class-uagb-post.php
  readme.txt
Labels: bug

#3001 SPCTR-2657: Fix: Columns block border-radius is not getting applied in frontend.
  README.md
  assets/css/blocks/column.css
  dist/blocks.style.css
  dist/style-blocks.css
  readme.txt
  src/blocks/column/style.scss
Labels: bug

#3010 SPCTR-2717 - Updated Changelog for v2.5.0
  README.md
  admin-core/ajax/common-settings.php
  blocks-config/uagb-controls/generateShadowCSS.js
  classes/class-uagb-block-helper.php
  classes/class-uagb-loader.php
  languages/ultimate-addons-for-gutenberg.pot
  package.json
  readme.txt
  ultimate-addons-for-gutenberg.php
Labels: ready-to-merge

#3019 SPCTR-2729 Countdown: Separator line height looks different on frontend (incorrect default)
  README.md
  includes/blocks/countdown/attributes.php
  readme.txt
Labels: bug

#3028 SPCTR-2735 Countdown - Innerblocks / Replace expiry option - Alignment fix for innerblocks
  assets/css/blocks/countdown.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/countdown/style.scss
Labels: bug

#3036 Spectra 2.5.0 Changelog Update
  README.md
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/pages/settings/MyAccount.js
  languages/ultimate-addons-for-gutenberg.pot
  readme.txt
Labels: ready-to-merge

#3012 SPCTR-2585-Fix counter initialisation issue in infinite slider loop
  .eslintrc.js
  README.md
  assets/js/spectra-counter.js
  assets/js/spectra-counter.min.js
  readme.txt
Labels: bug
