Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2023-03, with the labels that each got.

#2694 SPCTR-2323 fix: forms success message without adding 'To' email address field.
  README.md
  assets/js/forms.js
  assets/js/forms.min.js
  readme.txt
Labels: bug

#2761 SPCTR-2405- CTA - additional button icon hover color not reflecting/ not working on frontend
  README.md
  includes/blocks/call-to-action/frontend.css.php
  package-lock.json
  readme.txt
Labels: bug

#2773 SPCTR-2464: Image Gallery - Added Compatibility Between Image Sizes and Pagination Hotfix Features
  blocks-config/image-gallery/class-spectra-image-gallery.php
Labels: bug, php, frontend

#2788 Spectra 2.4.0 - Changelog
  README.md
  readme.txt
Labels: ready-to-merge

#2812 Fix: Post Timeline - Padding not working in the responsive devices on front-end
  classes/class-uagb-block-helper.php
  includes/blocks/content-timeline/frontend.css.php
Labels: bug

#2830 SPCTR-2494 Moved Spectra Menu to a Parent menu
  admin-core/inc/admin-menu.php
Labels: enhancement

#2819 Fix: SPCTR-2475- Taxonomy block - Translation missing for Select string in PHP file.
  README.md
  blocks-config/taxonomy-list/class-uagb-taxonomy-list.php
  readme.txt
Labels: bug

#2835 Imrpovement: Added Warning and Failed Settings Saved Notifications to the Admin Dashboard
  admin-core/assets/build/dashboard-app-rtl.css
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.css
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
  admin-core/assets/src/dashboard-app/pages/settings/RegenerateAssets.js
  admin-core/package-lock.json
  package-lock.json
Labels: enhancement, javascript, admin, ux

#2837 Improvement: Reworked Admin Settings Saved Notification for Dynamic Values
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
  dist/blocks.asset.php
Labels: enhancement, ready-to-merge, javascript, admin, ux

#2831 SPCTR-2476 Countdown Pro Evergreen - Added days feature
  assets/js/uagb-countdown.js
  assets/js/uagb-countdown.min.js
Labels: enhancement

#2882 PHP Doc Comment Update: Get Admin Settings Option
  classes/class-uagb-admin-helper.php
Labels: ready-to-merge

#2897 Fix: Removed Lightbox Margin for Flow Layouts
  assets/css/blocks/image-gallery.css
  dist/blocks.style.css
  dist/style-blocks.css
  src/blocks/image-gallery/style.scss
Labels: bug, css, frontend

#2904 Fix: Updated Date Time Picker to match the Spectra Standards
  dist/common-editor.css
  src/styles/gutenberg-override.scss
Labels: css, ux, editor

#2913 Improvement: Removed Unrequired Admin Localization
  admin-core/inc/admin-menu.php
Labels: ready-to-merge

#2767 SPCTR-2444-Improvement: Code: optimization of Spectra-settings functions in common-setting.php
  admin-core/ajax/common-settings.php
  admin-core/package-lock.json
  package-lock.json
Labels: php

#2914 SPCTR-2566 Countdown: Fix - Countdown takes time to start working on frontend
  assets/js/uagb-countdown.js
  assets/js/uagb-countdown.min.js
Labels: bug, ux
