Repository brainstormforce/ultimate-addons-for-gutenberg, pull requests merged in 2023-11, with the labels that each got.

#3588 Version control 2.9.1
  README.md
  classes/class-uagb-loader.php
  classes/class-uagb-post-assets.php
  languages/ultimate-addons-for-gutenberg.pot
  package-lock.json
  package.json
  readme.txt
  ultimate-addons-for-gutenberg.php
Labels: release-pr, Release PR

#3595 SPCTR-3504: Fix - Tabs wrapper margin is different in editor and frontend
  README.md
  assets/css/blocks/tabs.css
  dist/blocks.style.css
  dist/style-blocks.css
  readme.txt
  src/blocks/tabs/style.scss
Labels: bug

#3594 SPCTR-3487: Fix - Inline-Notice title is not in full width with Firefox browser
  README.md
  assets/css/blocks/inline-notice.css
  dist/blocks.style.css
  dist/style-blocks.css
  readme.txt
  src/blocks/inline-notice/style.scss
Labels: bug

#3606 Bumped Plugin Version to v2.10.1
  README.md
  classes/class-uagb-caching.php
  classes/class-uagb-loader.php
  languages/ultimate-addons-for-gutenberg.pot
  package-lock.json
  package.json
  readme.txt
  ultimate-addons-for-gutenberg.php
Labels: release-pr, Release PR

#3611 SPCTR-3525 - Zip AI: Added a Complete Disable Option to the Spectra Dashboard.
  admin-core/ajax/common-settings.php
  admin-core/assets/build/dashboard-app.asset.php
  admin-core/assets/build/dashboard-app.js
  admin-core/assets/src/dashboard-app/pages/settings/Settings.js
  admin-core/assets/src/dashboard-app/pages/settings/block-settings/ZipAISettings.js
  admin-core/assets/src/store/globalDataReducer.js
  admin-core/assets/src/store/globalDataStore.js
  admin-core/assets/src/utils/setInitialState.js
  admin-core/inc/admin-helper.php
  classes/class-uagb-admin-helper.php
  lib/zip-ai/admin/dashboard-app/build/dashboard-app.asset.php
  lib/zip-ai/admin/dashboard-app/build/dashboard-app.css
  lib/zip-ai/admin/dashboard-app/build/dashboard-app.js
  lib/zip-ai/classes/admin-configurations.php
  lib/zip-ai/classes/admin-views.php
  lib/zip-ai/classes/helper.php
  lib/zip-ai/classes/module.php
  lib/zip-ai/classes/sidebar-configurations.php
  lib/zip-ai/classes/utils.php
  lib/zip-ai/loader.php
  lib/zip-ai/sidebar/build/sidebar-app.asset.php
  lib/zip-ai/sidebar/build/sidebar-app.js
  lib/zip-ai/zip-ai.php
Labels: enhancement, php, javascript, admin, ux

#3625 SPCTR-3499: Fix - Container animation issue with Testimonial in Firefox browser.
  README.md
  assets/js/spectra-animations.js
  assets/js/spectra-animations.min.js
  readme.txt
Labels: bug

#3612 SPCTR-3506: Fix - Modal link component is not visible due to low z-index
  README.md
  assets/css/blocks/modal.css
  dist/blocks.style.css
  dist/style-blocks.css
  includes/blocks/modal/frontend.css.php
  readme.txt
  src/blocks/modal/style.scss
Labels: bug

#3627 SPCTR-3542 - Updated the AI Assistant Sidebar UI.
  assets/images/logos/spectra.svg
  classes/class-uagb-loader.php
  lib/zip-ai/classes/sidebar-configurations.php
  lib/zip-ai/scripts/IconComponents.js
  lib/zip-ai/sidebar/build/sidebar-app.asset.php
  lib/zip-ai/sidebar/build/sidebar-app.css
  lib/zip-ai/sidebar/build/sidebar-app.js
Labels: enhancement, editor
